name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: extractions/setup-just@v1
        with:
          just-version: 1.8.0
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build images
        shell: bash
        run: |
            set -exuo pipefail
            just build-nix-image
            just load-nix-image
            just build-image
      - name: Test image
        shell: bash
        run: just test-image
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          set -exuo pipefail
          just docker-login
          just push-image
